services:
  # This is your web service for real-time caption generation
  - type: web
    name: waffle-app-caption-service
    plan: free # Uses the free tier with spin-down behavior
    runtime: node

    # Specifies the sub-directory for this service
    # This is the most critical setting for the monorepo structure
    rootDir: render-backend

    # This section installs FFmpeg into the native Node.js environment
    #   probably not required sinc it should be installed by default when using native runtime
    # packages:
    #   - name: ffmpeg

    # Specifies build and start commands relative to the Root Directory
    buildCommand: "npm install"
    startCommand: "npm start"

    # Define environment variables. For secrets, 'sync: false' tells Render
    # to prompt for the value in the dashboard instead of storing it in git.
    envVars:
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_DB_URL # Full database connection string
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false